# Generated by Django 3.1.2 on 2020-10-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
