# Generated by Django 3.1.2 on 2020-10-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradeapp', '0002_grade_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('candidate', 'task')},
        ),
    ]
